### PR TITLE
Remove dependency on Bluebird

### PR DESCRIPTION
**Pull request by benesch**
WIP

### CODE REVIEW

**Comment by gaboesquivel** [comment]
@benesch  Correct me if I'm wrong. but I think this would remove support for `.finally()` which is pretty useful for testing. This is were I call `t.end()` or `done()`;

**Comment by benesch** [comment]
Hah, you're the GitHub hero I was hoping might turn up if I left this branch here. Yup, that's right. With this change, you'd have to import the module like so:

```
var BluebirdPromise = require("bluebird");
var request = require("supertest-as-promised")(BluebirdPromise);
```

To be honest, I'm not sure how I feel about this change, which is why it's been sitting here for a few days. It would be nice to ship without forcing a particular promise library on new users. But, at the same time, it's a change for the sake of a change and I'm not sure its worth breaking existing code. Thoughts?

**Comment by gaboesquivel** [comment]
@benesch  that's perfect. If you can use it with other promise libs I don't see a problem. Just bump the major and update readme ;) .

**Comment by benesch** [comment]
Use SuperTest 2.0 for exactly this functionality!

**Pull request closed without merging**
