### PR TITLE
added wait to return a delayed promise

### PR DESCRIPTION
**Pull request by LucioFranco**
Added a wait method to return a delayed promise.

### CODE REVIEW

**Comment by waisbrot** [comment]
Thanks! What's your use-case for this (why put the `wait` here instead of having the caller perform the wait)?

**Comment by LucioFranco** [comment]
So I figured out that there was already a method that does what I wanted inside bluebird (delay) but you could only call it after a then chain. The use case is for giving the express server time to do its work so that we have the ability to make another api call without an issue.

**Comment by benesch** [comment]
I feel your pain, but I'm not wild about shimming every useful method from Bluebird—of which there are many!—especially now that any promise library is supported.

When [ES6 proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) land, we can easily delegate missing methods to the underlying promise library.

**Comment by LucioFranco** [comment]
That makes sense and I saw that you just updated to 2.0.0. The .toPromise should do just fine. Thanks!

**Comment by benesch** [comment]
You bet! Thanks for the PR.

**Pull request closed without merging**
